# Generated by Django 4.0.1 on 2022-01-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='biology',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.studentinfo', unique=True),
        ),
    ]
