# Generated by Django 4.0.1 on 2022-01-13 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_studentacademics_biology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='roll_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.studentinfo'),
        ),
    ]
