# Generated by Django 4.0.1 on 2022-01-14 05:09

from django.db import migrations, models
import student_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_studentacademics_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademics',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=100, null=True, verbose_name=student_app.models.StudentInfo),
        ),
    ]
