# Generated by Django 4.0.1 on 2022-01-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_studentacademics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentacademics',
            name='name',
        ),
    ]
